name: ML Pipeline CI

on:
  push:
    branches: [ main, master  ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  actions: write 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest great_expectations pandas scikit-learn flake8 black mypy pytest-cov gh
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        flake8 day5/演習3 --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 day5/演習3 --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
        
    - name: Format check with black
      run: |
        black --check day5/演習3
        
    - name: Run data tests
      run: |
        pytest day5/演習3/tests/test_data.py -v -s
        
    - name: Run model tests
      run: |
        pytest day5/演習3/tests/test_model.py -v -s
    
    - name: Run model tests and get accuracy
      id: model_test
      run: |
          cd day5/演習3/tests
          pytest test_model.py -v -s --capture-output # 標準出力をキャプチャ

    - name: Update baseline accuracy (if tests passed)
      if: success()
      run: |
          import re
          accuracy_output = ${{ steps.model_test.outputs.stdout }}
          # ログから現在の精度を抽出する (pytest の出力形式に合わせて調整)
          current_accuracy_match = re.search(r"現在のモデルの精度\((\d+\.\d+)\)", accuracy_output)
          if current_accuracy_match:
            current_accuracy=$(echo "${current_accuracy_match[1]}" | awk '{printf "%.4f", $1}')
            echo "Updating BASELINE_ACCURACY to: $current_accuracy"
            gh variable set BASELINE_ACCURACY "$current_accuracy"
          else:
            echo "Could not extract current accuracy from logs."
            exit 1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
