name: ML Pipeline CI

on:
  push:
    branches: [ main, master  ]
  pull_request:
    branches: [ main, master,develop ]

permissions:
  contents: read
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest
    environment: BASE_ACCURACY # デプロイ先環境を 'development' に固定
    steps:
    - uses: actions/checkout@v3
    - name: Clear environment # テスト的に追加
      run: |
        env -i bash -c "env"
    # ... (セットアップ、依存関係インストールなど)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest great_expectations pandas scikit-learn flake8 black mypy pytest-cov gh
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run model tests
      run: |
        echo "BASELINE_ACCURACY from vars: ${{ vars.BASELINE_ACCURACY }}" # 確認用
        echo "BASELINE_ACCURACY from env: ${{ env.BASELINE_ACCURACY }}"   # 確認用
        python -c "import os; print(f'BASELINE_ACCURACY from os: {os.environ.get(\"BASELINE_ACCURACY\")}')" # 確認用
        pytest day5/演習3/tests/test_model.py -v -s
      env:
        BASELINE_ACCURACY: ${{ vars.BASELINE_ACCURACY }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    
    - name: Lint with flake8
      run: |
